### ISSUE TITLE
PAM support

### ISSUE THREAD

**Issue by OtherSystems** [binary-manu/static-cross-openssh#1]
Hi!

This is pretty neat, but is there a way to add PAM support? 

Thanks.

**Comment by binary-manu** [comment]
At a glance, the answer is likely no.

PAM revolves around dynamically loading modules based on the contents of configuration files. So even if libpam itself could be statically linked into SSH, modules would still require a dynamic linker in place, which defeats the purpose of this repo.

Also, if modules are built statically, since they expose identically named symbols to be looked up via `dlsym`, they would conflict when linking.
