### ISSUE TITLE
OpenSSL 1.1.1X vs 3.0.X vs 3.1.X

### ISSUE THREAD

**Issue by Azathothas** [binary-manu/static-cross-openssh#2]
Hi, sorry if this is a dumb question, but 
> what's the difference between the major versions listed on: https://www.openssl.org ?

```console
9661 | 2023-Aug-01 14:09:08 | openssl-1.1.1v.tar.gz (SHA256) (PGP sign) (SHA1)
14838 | 2023-Aug-01 14:09:08 | openssl-3.0.10.tar.gz (SHA256) (PGP sign) (SHA1)
15195 | 2023-Aug-01 14:09:08 | openssl-3.1.2.tar.gz (SHA256) (PGP sign) (SHA1)
```

And
> why does the [toolchain.mk](https://github.com/binary-manu/static-cross-openssh/blob/master/toolchain.mk) use `1.1.X` ?

**Comment by binary-manu** [comment]
Hi. OpenSSL 3.0 is a new major release which does not guarantee backward compatibility with previous versions. Also, the license has been changed, as well as the versioning scheme. So, if your app is using v1.1.1 you must recompile it against v3.x, and it may also require some code modifications if you are using APIs that have changed.

> Main Changes from OpenSSL 1.1.1
> 
> Major Release
> 
> OpenSSL 3.0 is a major release and consequently any application that currently
> uses an older version of OpenSSL will at the very least need to be recompiled
> in order to work with the new version. It is the intention that the large
> majority of applications will work unchanged with OpenSSL 3.0 if those
> applications previously worked with OpenSSL 1.1.1. However this is not
> guaranteed and some changes may be required in some cases. Changes may also be
> required if applications need to take advantage of some of the new features
> available in OpenSSL 3.0 such as the availability of the FIPS module.
> License Change
> 
> In previous versions, OpenSSL was licensed under the dual OpenSSL and SSLeay
> licenses (both licenses apply). From OpenSSL 3.0 this is replaced by the Apache
> License v2.

As for v3.0 vs v3.1, v3.0 is an LTS (Long Term Support) release, which will be supported for a long time, while v3.1 is not:

> 3.1 is unlikely to be supported for as long as 3.0 due to the latter being
> an LTS release.
>
> We generally recommend using the most recent supported release (i.e. 3.1).
>
> 3.1 includes a number of performance fixes and enhancements over 3.0.
>
> We do not yet have a plan for supporting the 3.1 FIPS provider once it is
> validated. I expect it will receive support until it is sunsetted but that's
>not decided at this point.
>
> Both 3.0 and 3.1 should be able to co-exist.

Finally, [openssh-portable](https://github.com/openssh/openssh-portable) (the version of OpenSSH that works outside OpenBSD) requires at least  OpenSSL 1.1.1 to work:

> libcrypto from either of LibreSSL or OpenSSL.  Building without libcrypto
> is supported but severely restricts the available ciphers and algorithms.
>  - LibreSSL (https://www.libressl.org/) 3.1.0 or greater
>  - OpenSSL (https://www.openssl.org) 1.1.1 or greater

The script I used as a basis from my repo used 1.1.1, so I stick with it. That version is still being updated so there is no compelling need to update. Also, doing so may require code changes to OpenSSH itself. The OpenSSL version will be updated when OpenSSH starts requiring at least OpenSSL v3.x.

**Comment by Azathothas** [comment]
Thanks for replying.

I forked this repo and made **few** changes that do not rely on hardcoded values (Such as Version Number for OpenSSH, Bootlin Toolchains & Zlib).
I wondered about your script using OpenSSL `1.1.1u`, which wasn't even listed on OpenSSL's page.

Further, I tested some builds (`x86-64`, `aarch64` & `armv7-eabihf`) to see if they would compile with `openssl-3.1.2`.
Indeed, they do:   
https://github.com/Azathothas/static-toolbox/releases/tag/openssh-V_9_4_P1

Could we put a regular releaser for new versions of OpenSSH using GitHub Actions?
Pre-Built Binaries would be very helpful!

**Comment by binary-manu** [comment]
I looked at your code. I like the idea of always building the latest version, which would eliminate the need to periodically update the Makefiles. However, I also want to keep a way to force specific versions to be used, so that we can tag commits that yield "reproducible" builds (as far as the versions are concerned).

We could add a conditional mechanism to the Makefiles which override hardwired versions with values from the repos if some condition is met. For example, if `zlib/VERSION` is empty because we have overridden it from the CLI or CI, then go fetch the version from GitHub; otherwise, use the value from the Makefile, the last "known to be good" version.

As for CI builds, that would be nice but I don't know how to use GitHub actions, since I routinely use Gitlab CI at work. I would accept contributions tough. However, we should define which architectures make sense for a prebuilt deliverable (I would say `armv7-eabihf` and `aarch64`, `x86-64` *could* be useful inside some very basic VM, but realistically any full-blown x86-64 system will ship its own version and most embedded boards will use a different ISA). We must also define prefix paths for builds: most builds could just use `/opt/openssh` (I think it's better not to use `/usr/local` to keep the release under a single root folder). For Android, which does not conform to the FHS, `/system/opt/openssh` has worked fine so far.

**Comment by binary-manu** [comment]
Hello. There are some news.

I have updated the makefiles to support using the latest versions of packages and the toolchain automatically. This does not happen by default, but must be enabled for individual packages, the toolchain, or globally via make variables.

You may take a look at tag v0.1.4 for the modifications.

Given this new foundation, it is now feasible to try to automatically build binary release for the latest and greatest periodically. I have started using CircleCI for another project, so I'll try to come up with something to do the build maybe monthly.

As for the architectures and prefixes, I was thinking of the following:

* x86-64/`/opt/openssh/$VERSION`
* armv7/`/opt/openssh/$VERSION`
* aarch64/`/opt/openssh/$VERSION`
* armv7/`/system/opt/openssh/$VERSION`
* aarch64/`/system/opt/openssh/$VERSION`

The last two versions are for Android devices, which will likely use /system to store this stuff (at least this is what I did on my rooted phone, but it was Android 8.1 so this may no longer be useful).

**Comment by binary-manu** [comment]
I prepared a crude pipeline on CircleCI which builds the deliverables above (without `$VERSION` in the prefix) and uploads them as CI artifacts. The docs now have a link to the pipeline page.

I know this is not as fancy as GitHub listing the releases, but it seems to work. Improvements may come over time.
