### ISSUE TITLE
[Request] Make additional Binaries

### ISSUE THREAD

**Issue by Azathothas** [binary-manu/static-cross-openssh#4]
Currently, only:
```bash
https://output.circle-artifacts.com/output/job/ec43570c-d08b-4d0d-887a-b5ac8e61b6d7/artifacts/0/artifacts/openssh-x86-64.tgz
(1) opt/openssh/sbin/sshd
(2) opt/openssh/libexec/sftp-server
```
would be nice to also have:
```bash
scp
sftp
ssh
ssh-add
ssh-agent
ssh-keygen
ssh-keyscan
ssh-keysign
```

**Comment by binary-manu** [comment]
I've added the requested executables to the package, since they were already being built. They are available for all architectures.

At the moment, this is unmerged and available on the branch `feature/extra-bins`.

@Azathothas Can you give it a try? I'm busy with some other stuff right now and don't have the time to do some proper testing. If you find it to be OK, I'll merge. You can use the artifacts from [this pipeline](https://app.circleci.com/pipelines/github/binary-manu/static-cross-openssh/10/workflows/f616b814-c224-4551-bf3b-7ad4dd8c5717/jobs/9/artifacts)

**Comment by Azathothas** [comment]
Thanks for making this so quickly.

```bash
https://output.circle-artifacts.com/output/job/9fc46489-8096-49a0-a9a7-64af1980d6d8/artifacts/0/artifacts/openssh-x86-64.tgz
(1) opt/openssh/sbin/sshd
(2) opt/openssh/bin/ssh
(3) opt/openssh/bin/scp
(4) opt/openssh/bin/ssh-add
(5) opt/openssh/bin/ssh-agent
(6) opt/openssh/bin/ssh-keygen
(7) opt/openssh/bin/ssh-keyscan
(8) opt/openssh/bin/sftp
(9) opt/openssh/libexec/sftp-server
(10) opt/openssh/libexec/ssh-keysign
(11) opt/openssh/etc/sshd_config
```

 I tested all these on an `x86_64` system (very minimal debian with nthg installed), and all of them work as expected.

**Comment by binary-manu** [comment]
Merge done, now the automated monthly build will produce the requested additional binaries.
The latest `master` pipeline artifacts already contain them all.
